const seed=[
{id:1,name:'フシギダネ',kind:'たねポケモン',type:'くさ'},{id:4,name:'ヒトカゲ',kind:'とかげポケモン',type:'ほのお'},{id:7,name:'ゼニガメ',kind:'かめのこポケモン',type:'みず'},{id:25,name:'ピカチュウ',kind:'ねずみポケモン',type:'でんき'},{id:133,name:'イーブイ',kind:'しんかポケモン',type:'ノーマル'},{id:143,name:'カビゴン',kind:'いねむりポケモン',type:'ノーマル'}
];
const $=s=>document.querySelector(s),pad=n=>String(n).padStart(3,'0'),config=window.FUTARI_DEX_CONFIG||{},room=config.room||'futari-dex',canSync=Boolean(config.supabaseUrl&&config.supabaseAnonKey),toKatakana=t=>t.replace(/[ぁ-ゖ]/g,c=>String.fromCharCode(c.charCodeAt(0)+0x60)),toHiragana=t=>t.replace(/[ァ-ヺ]/g,c=>String.fromCharCode(c.charCodeAt(0)-0x60));
const memberNames=$('#memberNames');if(memberNames&&config.members)memberNames.textContent=config.members;
const dex=new Map(seed.map(p=>[p.name,{...p,sprite:`https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/${p.id}.png`,shiny:`https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/${p.id}.png`}]));
let authToken=localStorage.getItem('futari-dex-token')||'',selected=null,uploadedPhotos=[],coordinates=null,editId=null,editPhotos=[],dexView='all',toastTimer,dateEdited=false,worldMap=null,mapMarkers=[];
const headers=()=>({apikey:config.supabaseAnonKey,Authorization:`Bearer ${authToken||config.supabaseAnonKey}`});
function parsePhotos(p){if(Array.isArray(p.photos))return p.photos.filter(Boolean);if(!p.photo)return[];try{const parsed=JSON.parse(p.photo);return Array.isArray(parsed)?parsed.filter(Boolean):[p.photo]}catch{return[p.photo]}}
function dexNo(p){return p.dex_no??(p.id<2000?p.id:dex.get(p.name)?.id??p.id)}
function unpackRecordDate(value){if(!value)return{encounterDate:'',note:''};try{const parsed=JSON.parse(value);if(parsed&&typeof parsed==='object')return{encounterDate:parsed.encounterDate||'',note:parsed.note||''}}catch{}return /^\d{4}-\d{2}-\d{2}$/.test(value)?{encounterDate:value,note:''}:{encounterDate:'',note:value}}
const packRecordDate=p=>JSON.stringify({encounterDate:p.encounterDate||'',note:p.note||''});
const today=()=>new Date().toISOString().slice(0,10);
const formatDate=value=>value?new Intl.DateTimeFormat('ja-JP',{year:'numeric',month:'long',day:'numeric'}).format(new Date(`${value}T00:00:00`)):'';
function normalise(records){const grouped=new Map();records.filter(p=>p.type!=='__deleted__').forEach(raw=>{const no=dexNo(raw),base=dex.get(raw.name)||{},info=unpackRecordDate(raw.date),old=grouped.get(no)||{id:no,name:base.name||raw.name,kind:base.kind||raw.kind||'ポケモン',type:base.type||raw.type||'みつけた',sprite:base.sprite||raw.sprite||`https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/${no}.png`,shiny:base.shiny||`https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/${no}.png`,photos:[],encounterDate:info.encounterDate,note:info.note,place:raw.place||'',lat:raw.lat,lng:raw.lng};old.photos=[...new Set([...old.photos,...parsePhotos(raw)])];if(info.encounterDate)old.encounterDate=info.encounterDate;if(info.note)old.note=info.note;if(raw.place)old.place=raw.place;if(raw.lat!=null)old.lat=raw.lat;if(raw.lng!=null)old.lng=raw.lng;grouped.set(no,old)});return[...grouped.values()]}
let collection=normalise(JSON.parse(localStorage.getItem('futari-dex')||'[]'));
const saveLocal=()=>localStorage.setItem('futari-dex',JSON.stringify(collection));
function showToast(text){const node=$('#toast');node.textContent=text;node.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>node.classList.remove('show'),2600)}
function fillSuggestions(){const names=[...dex.keys()],values=[...new Set([...names,...names.map(toHiragana)])].sort((a,b)=>a.localeCompare(b,'ja'));$('#pokemonSuggestions').innerHTML=values.map(name=>`<option value="${name}"></option>`).join('')}
async function loadNationalDex(){try{const cached=localStorage.getItem('futari-national-dex');let entries;if(cached)entries=Object.entries(JSON.parse(cached));else{const text=await fetch('https://raw.githubusercontent.com/PokeAPI/pokeapi/master/data/v2/csv/pokemon_species_names.csv').then(r=>r.text()),index={};text.split('\n').slice(1).forEach(row=>{const c=row.split(',');if(c[1]==='11'&&c[2])index[c[2].replaceAll('"','')]=Number(c[0])});localStorage.setItem('futari-national-dex',JSON.stringify(index));entries=Object.entries(index)}entries.forEach(([name,id])=>dex.set(name,{id:Number(id),name,kind:'ポケモン',type:'みつけた',sprite:`https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/${id}.png`,shiny:`https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/${id}.png`}));collection=normalise(collection);saveLocal();fillSuggestions();render()}catch(error){console.warn(error);fillSuggestions()}}
function visibleDex(){if(dexView==='caught')return collection;return[...dex.values()].map(p=>collection.find(c=>c.id===p.id)||{...p,photos:[],unknown:true})}
function render(){const list=$('#dexList');list.innerHTML='';visibleDex().sort((a,b)=>a.id-b.id).forEach(p=>{const caught=!p.unknown,n=$('#dexItemTemplate').content.cloneNode(true),card=n.querySelector('.dex-item'),photo=n.querySelector('.entry-photo'),normal=n.querySelector('.normal-sprite'),shiny=n.querySelector('.shiny-sprite');card.classList.toggle('unknown',!caught);photo.src=p.photos?.[0]||p.sprite;photo.alt=caught?p.name:'未登録のポケモン';normal.querySelector('img').src=p.sprite;shiny.querySelector('img').src=p.shiny;normal.hidden=!( !caught || (caught&&p.photos?.length));shiny.hidden=!caught;n.querySelector('.dex-no').textContent=`No.${pad(p.id)}`;n.querySelector('h3').textContent=caught?p.name:'？？？';n.querySelector('.type-pill').textContent=caught?p.type:'未登録';n.querySelector('.encounter').textContent=caught?([formatDate(p.encounterDate),p.place].filter(Boolean).join('・')||p.note||'まだ思い出はありません'):'見つけると登録できます';if(caught)card.onclick=()=>openEntry(p.id);list.append(n)});$('#seenCount').textContent=pad(collection.length);$('#photoCount').textContent=pad(collection.reduce((n,p)=>n+p.photos.length,0));$('#progressBar').style.width=`${Math.max(.1,collection.length/1025*100)}%`;$('#albumGrid').innerHTML=collection.flatMap(p=>p.photos.map(photo=>`<div class="album-card"><img src="${photo}" alt="${p.name}の写真"><span>No.${pad(p.id)} ${p.name}</span></div>`)).join('')||'<p>まだ写真がありません。</p>';renderMap()}
function setupWorldMap(){if(worldMap||!window.L)return Boolean(worldMap);worldMap=L.map('memoryMap',{worldCopyJump:true,minZoom:2,maxZoom:19,zoomControl:true}).setView([20,0],2);L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'}).addTo(worldMap);setTimeout(()=>worldMap.invalidateSize(),0);return true}
function renderMap(){const located=collection.filter(p=>Number.isFinite(p.lat)&&Number.isFinite(p.lng)),places=$('#placeList');if(!setupWorldMap()){places.innerHTML='<div class="place-card"><span class="place-dot"></span><small>地図を読み込めませんでした。通信を確認してね。</small></div>';return}mapMarkers.forEach(marker=>marker.remove());mapMarkers=[];located.forEach((p,i)=>{const marker=L.circleMarker([p.lat,p.lng],{radius:10,color:'#fff',weight:3,fillColor:'#ef4960',fillOpacity:1}).addTo(worldMap).bindTooltip(`${i+1}. ${p.name}`,{direction:'top'}).on('click',()=>openEntry(p.id));mapMarkers.push(marker)});if(!located.length){places.innerHTML='<div class="place-card"><span class="place-dot"></span><small>まだ位置情報がありません。「今いる場所を記録」でピンを追加できます。</small></div>';return}places.innerHTML=located.map(p=>`<div class="place-card"><span class="place-dot"></span><div><strong>${p.name} — ${p.place||'場所未入力'}</strong><small>${p.lat.toFixed(5)}, ${p.lng.toFixed(5)}</small></div><button class="edit-place" data-id="${p.id}">編集</button></div>`).join('');places.querySelectorAll('.edit-place').forEach(b=>b.onclick=()=>openEntry(Number(b.dataset.id)))}
function updateRegistration(){const raw=$('#nameInput').value.trim(),match=dex.get(toKatakana(raw)),status=$('#nameStatus');if(match){selected=match;$('#resultName').textContent=match.name;$('#resultMeta').textContent=`No.${pad(match.id)} ・ ${match.kind}`;$('#resultSprite').style.backgroundImage=`url(${match.sprite})`;$('#resultCard').hidden=false;status.classList.add('found');status.lastElementChild.textContent=`No.${pad(match.id)} に登録します`}else{selected=null;$('#resultCard').hidden=true;status.classList.remove('found');status.lastElementChild.textContent=raw?'名前を探しています。':'名前を入力すると図鑑へ振り分けます'}$('#saveBtn').disabled=!raw;$('#saveBtn').classList.toggle('ready',Boolean(raw))}
function compressPhoto(file){return new Promise((resolve,reject)=>{const url=URL.createObjectURL(file),image=new Image();image.onload=()=>{const scale=Math.min(1,960/Math.max(image.naturalWidth,image.naturalHeight)),canvas=document.createElement('canvas');canvas.width=Math.round(image.naturalWidth*scale);canvas.height=Math.round(image.naturalHeight*scale);canvas.getContext('2d').drawImage(image,0,0,canvas.width,canvas.height);URL.revokeObjectURL(url);resolve(canvas.toDataURL('image/jpeg',.68))};image.onerror=()=>reject(new Error('photo'));image.src=url})}
async function uploadPhotos(p){if(!canSync||!authToken)return;for(let i=0;i<p.photos.length;i++){if(!p.photos[i].startsWith('data:'))continue;const blob=await(await fetch(p.photos[i])).blob(),path=`${room}/${p.id}-${i}.jpg`,r=await fetch(`${config.supabaseUrl}/storage/v1/object/dex-photos/${path}`,{method:'POST',headers:{...headers(),'Content-Type':'image/jpeg','x-upsert':'true'},body:blob});if(!r.ok)throw new Error('写真アップロードに失敗しました');p.photos[i]=`${config.supabaseUrl}/storage/v1/object/public/dex-photos/${path}`}}
async function sync(){if(!canSync)throw new Error('config.js のSupabase設定がありません');if(!authToken)throw new Error('右上のMからログインしてください');const uploads=await Promise.allSettled(collection.map(uploadPhotos)),payload=collection.map(p=>({id:p.id,room,name:p.name,kind:p.kind,type:p.type,sprite:p.sprite,photo:JSON.stringify(p.photos),date:packRecordDate(p),place:p.place||null,lat:p.lat??null,lng:p.lng??null})),r=await fetch(`${config.supabaseUrl}/rest/v1/entries?on_conflict=room,id`,{method:'POST',headers:{...headers(),'Content-Type':'application/json',Prefer:'resolution=merge-duplicates'},body:JSON.stringify(payload)});if(!r.ok){const problem=await r.json().catch(()=>({}));throw new Error(problem.message||`通信エラー ${r.status}`)}saveLocal();if(uploads.some(x=>x.status==='rejected'))showToast('図鑑は共有済み。写真は次回再同期します')}
async function loadShared(replace=false){if(!canSync||!authToken)return false;try{const r=await fetch(`${config.supabaseUrl}/rest/v1/entries?room=eq.${encodeURIComponent(room)}&select=*`,{headers:headers()});if(!r.ok)throw new Error(`通信エラー ${r.status}`);const shared=await r.json();if(Array.isArray(shared)){const remote=normalise(shared);if(replace)collection=remote;else{const merged=new Map(remote.map(p=>[p.id,p]));collection.forEach(p=>{if(!merged.has(p.id))merged.set(p.id,p)});collection=[...merged.values()]}saveLocal();render();return true}}catch(error){console.warn(error);return false}}
async function refreshShared(){if(!canSync||!authToken){showToast('右上のMからログインしてください');return}showToast('共有データを更新中…');if(await loadShared(true))showToast('最新の共有データに更新したよ！');else showToast('更新できませんでした。通信を確認してね')}
function resetForm(){$('#captureForm').reset();uploadedPhotos=[];selected=coordinates=null;dateEdited=false;$('#encounterDateInput').value=today();$('#photoPreview').className='picker-inner';$('#photoPreview').style.backgroundImage='';$('#resultCard').hidden=true;updateRegistration();$('#locationState').textContent='場所はあとから編集できます'}
async function saveEntry(){const raw=$('#nameInput').value.trim(),p=selected;if(!raw){showToast('名前を入れてね');return}if(!p){showToast('候補からポケモンを選んでね');return}let entry=collection.find(item=>item.id===p.id),isNew=!entry;if(!entry){entry={...p,photos:[],encounterDate:'',note:'',place:'',lat:null,lng:null};collection.push(entry)}if(uploadedPhotos.length)entry.photos.push(...uploadedPhotos);entry.photos=[...new Set(entry.photos)];entry.encounterDate=(isNew||dateEdited?$('#encounterDateInput').value:entry.encounterDate)||today();entry.note=$('#noteInput').value.trim()||entry.note||'';entry.place=$('#locationInput').value.trim()||entry.place;if(coordinates){entry.lat=coordinates.lat;entry.lng=coordinates.lng}saveLocal();render();$('#captureDialog').close();resetForm();showToast(`${p.name} を図鑑に登録したよ！`);try{await sync()}catch(error){showToast(`端末には保存済み：${error.message}`)}}
function renderEntryPhotos(){const root=$('#entryPhotos');if(!editPhotos.length){root.innerHTML='<p class="photo-empty">写真はまだありません。下のボタンからライブラリを開けます。</p>';return}root.innerHTML=editPhotos.map((src,i)=>`<div class="entry-photo-edit"><img src="${src}" alt="写真 ${i+1}"><div class="photo-actions"><button type="button" data-photo-move="-1" data-index="${i}" aria-label="前へ">‹</button><button type="button" data-photo-move="1" data-index="${i}" aria-label="次へ">›</button><button type="button" class="photo-remove" data-photo-remove="${i}" aria-label="写真を削除">×</button></div></div>`).join('');root.querySelectorAll('[data-photo-move]').forEach(button=>button.onclick=()=>{const i=Number(button.dataset.index),next=i+Number(button.dataset.photoMove);if(next<0||next>=editPhotos.length)return;[editPhotos[i],editPhotos[next]]=[editPhotos[next],editPhotos[i]];renderEntryPhotos()});root.querySelectorAll('[data-photo-remove]').forEach(button=>button.onclick=()=>{editPhotos.splice(Number(button.dataset.photoRemove),1);renderEntryPhotos()})}
function openEntry(id){const p=collection.find(item=>item.id===id);if(!p)return;editId=id;editPhotos=[...p.photos];$('#entryTitle').textContent=`${p.name} のきろく`;$('#entrySprite').src=p.sprite;$('#entryNo').textContent=`No.${pad(p.id)}`;$('#entryName').textContent=p.name;$('#entryKind').textContent=p.kind;renderEntryPhotos();$('#editDateInput').value=p.encounterDate||'';$('#editNoteInput').value=p.note||'';$('#editPlaceInput').value=p.place||'';$('#editPhotoInput').value='';$('#entryDialog').showModal()}
function accountState(){const logged=Boolean(authToken);$('#accountHelp').textContent=logged?'この端末は図鑑アカウントにログイン中です。':'二人とも同じメールアドレスとパスワードでログインします。';$('#loginButton').hidden=logged;$('#signupButton').hidden=logged;$('#logoutButton').hidden=!logged;$('#accountButton').textContent=logged?'✓':'M'}
async function auth(mode){if(!canSync){$('#accountHelp').textContent='先に config.js を設定してください。';return}const email=$('#emailInput').value.trim(),password=$('#passwordInput').value;if(!email||password.length<6){$('#accountHelp').textContent='メールアドレスと6文字以上のパスワードを入力してください。';return}const r=await fetch(`${config.supabaseUrl}/auth/v1/${mode==='login'?'token?grant_type=password':'signup'}`,{method:'POST',headers:{apikey:config.supabaseAnonKey,'Content-Type':'application/json'},body:JSON.stringify({email,password})}),data=await r.json();if(!r.ok){$('#accountHelp').textContent=data.message||data.msg||'ログインできません。';return}if(!data.access_token){$('#accountHelp').textContent='メール確認後にログインしてください。';return}authToken=data.access_token;localStorage.setItem('futari-dex-token',authToken);accountState();await loadShared(true);$('#accountDialog').close()}
$('#openCapture').onclick=$('#captureCta').onclick=()=>{resetForm();$('#captureDialog').showModal()};$('#nameInput').oninput=updateRegistration;$('#encounterDateInput').oninput=()=>dateEdited=true;$('#photoInput').onchange=async e=>{const files=[...e.target.files];if(!files.length)return;try{uploadedPhotos=await Promise.all(files.map(compressPhoto));const preview=$('#photoPreview');preview.classList.add('preview');preview.style.backgroundImage=`url(${uploadedPhotos[0]})`;showToast(`${uploadedPhotos.length}枚の写真を選んだよ`)}catch{showToast('写真を読み込めませんでした')}};$('#locateBtn').onclick=()=>navigator.geolocation?.getCurrentPosition(p=>{coordinates={lat:p.coords.latitude,lng:p.coords.longitude};$('#locationState').textContent='位置情報を記録しました'},()=>$('#locationState').textContent='場所名だけでも登録できます');window.futariSaveEntry=saveEntry;$('#captureForm').onsubmit=e=>{e.preventDefault();saveEntry()};
$('#editPhotoInput').onchange=async e=>{const files=[...e.target.files];if(!files.length)return;try{editPhotos.push(...await Promise.all(files.map(compressPhoto)));renderEntryPhotos();e.target.value='';showToast('写真を追加したよ。保存してね')}catch{showToast('写真を読み込めませんでした')}};$('#entryForm').onsubmit=async e=>{e.preventDefault();const p=collection.find(item=>item.id===editId);if(!p)return;p.encounterDate=$('#editDateInput').value||p.encounterDate||today();p.note=$('#editNoteInput').value.trim();p.place=$('#editPlaceInput').value.trim()||p.place;p.photos=[...editPhotos];saveLocal();render();$('#entryDialog').close();try{await sync();showToast('変更を保存したよ！')}catch(error){showToast(`端末には保存済み：${error.message}`)}};
$('#deleteEntryButton').onclick=async()=>{const p=collection.find(item=>item.id===editId);if(!p||!confirm(`${p.name} を削除しますか？`))return;collection=collection.filter(item=>item.id!==p.id);saveLocal();render();$('#entryDialog').close();try{await fetch(`${config.supabaseUrl}/rest/v1/entries?room=eq.${encodeURIComponent(room)}&id=eq.${p.id}`,{method:'DELETE',headers:headers()});showToast('削除したよ')}catch{showToast('端末から削除したよ')}};
document.querySelectorAll('[data-dex-view]').forEach(button=>button.onclick=()=>{dexView=button.dataset.dexView;document.querySelectorAll('[data-dex-view]').forEach(b=>b.classList.toggle('active',b===button));render()});document.querySelectorAll('.tabs button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tabs button,.tab-panel').forEach(e=>e.classList.remove('active'));b.classList.add('active');$('#'+b.dataset.tab).classList.add('active');if(b.dataset.tab==='map'&&worldMap)setTimeout(()=>worldMap.invalidateSize(),0)});const openTab=id=>{document.querySelector(`.tabs button[data-tab="${id}"]`).click();$('#menuDialog').close()};$('#menuDex').onclick=()=>openTab('dex');$('#menuMap').onclick=()=>openTab('map');$('#menuAlbum').onclick=()=>openTab('album');$('#menuRefresh').onclick=async()=>{await refreshShared();$('#menuDialog').close()};$('#accountButton').onclick=()=>$('#accountDialog').showModal();$('#loginButton').onclick=()=>auth('login');$('#signupButton').onclick=()=>auth('signup');$('#logoutButton').onclick=()=>{authToken='';localStorage.removeItem('futari-dex-token');accountState();$('#accountDialog').close()};
$('#menuDialog').onclick=null;$('#menuButton').onclick=()=>$('#menuDialog').showModal();
document.querySelectorAll('dialog').forEach(dialog=>dialog.addEventListener('click',event=>{if(event.target===dialog)dialog.close()}));
accountState();fillSuggestions();resetForm();render();loadNationalDex();loadShared(true);
