const seed=[
{id:1,name:'フシギダネ',kind:'たねポケモン',type:'くさ'},{id:4,name:'ヒトカゲ',kind:'とかげポケモン',type:'ほのお'},{id:7,name:'ゼニガメ',kind:'かめのこポケモン',type:'みず'},{id:25,name:'ピカチュウ',kind:'ねずみポケモン',type:'でんき'},{id:133,name:'イーブイ',kind:'しんかポケモン',type:'ノーマル'},{id:143,name:'カビゴン',kind:'いねむりポケモン',type:'ノーマル'}
];
const $=s=>document.querySelector(s),pad=n=>String(n).padStart(3,'0'),config=window.FUTARI_DEX_CONFIG||{},room=config.room||'futari-dex',canSync=Boolean(config.supabaseUrl&&config.supabaseAnonKey),toKatakana=t=>t.replace(/[ぁ-ゖ]/g,c=>String.fromCharCode(c.charCodeAt(0)+0x60)),toHiragana=t=>t.replace(/[ァ-ヺ]/g,c=>String.fromCharCode(c.charCodeAt(0)-0x60));
const dex=new Map(seed.map(p=>[p.name,{...p,sprite:`https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/${p.id}.png`,shiny:`https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/${p.id}.png`}]));
let authToken=localStorage.getItem('futari-dex-token')||'',selected=null,uploadedPhoto=null,coordinates=null,editId=null,editPhoto=null,dexView='all',toastTimer;
const headers=()=>({apikey:config.supabaseAnonKey,Authorization:`Bearer ${authToken||config.supabaseAnonKey}`});
function parsePhotos(p){if(Array.isArray(p.photos))return p.photos.filter(Boolean);if(!p.photo)return[];try{const parsed=JSON.parse(p.photo);return Array.isArray(parsed)?parsed.filter(Boolean):[p.photo]}catch{return[p.photo]}}
function dexNo(p){return p.dex_no??(p.id<2000?p.id:dex.get(p.name)?.id??p.id)}
function normalise(records){const grouped=new Map();records.filter(p=>p.type!=='__deleted__').forEach(raw=>{const no=dexNo(raw),base=dex.get(raw.name)||{},old=grouped.get(no)||{id:no,name:base.name||raw.name,kind:base.kind||raw.kind||'ポケモン',type:base.type||raw.type||'みつけた',sprite:base.sprite||raw.sprite||`https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/${no}.png`,shiny:base.shiny||`https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/${no}.png`,photos:[],date:raw.date||'',place:raw.place||'',lat:raw.lat,lng:raw.lng};old.photos=[...new Set([...old.photos,...parsePhotos(raw)])];if(raw.date)old.date=raw.date;if(raw.place)old.place=raw.place;if(raw.lat!=null)old.lat=raw.lat;if(raw.lng!=null)old.lng=raw.lng;grouped.set(no,old)});return[...grouped.values()]}
let collection=normalise(JSON.parse(localStorage.getItem('futari-dex')||'[]'));
const saveLocal=()=>localStorage.setItem('futari-dex',JSON.stringify(collection));
function showToast(text){const node=$('#toast');node.textContent=text;node.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>node.classList.remove('show'),2600)}
function fillSuggestions(){const names=[...dex.keys()],values=[...new Set([...names,...names.map(toHiragana)])].sort((a,b)=>a.localeCompare(b,'ja'));$('#pokemonSuggestions').innerHTML=values.map(name=>`<option value="${name}"></option>`).join('')}
async function loadNationalDex(){try{const cached=localStorage.getItem('futari-national-dex');let entries;if(cached)entries=Object.entries(JSON.parse(cached));else{const text=await fetch('https://raw.githubusercontent.com/PokeAPI/pokeapi/master/data/v2/csv/pokemon_species_names.csv').then(r=>r.text()),index={};text.split('\n').slice(1).forEach(row=>{const c=row.split(',');if(c[1]==='11'&&c[2])index[c[2].replaceAll('"','')]=Number(c[0])});localStorage.setItem('futari-national-dex',JSON.stringify(index));entries=Object.entries(index)}entries.forEach(([name,id])=>dex.set(name,{id:Number(id),name,kind:'ポケモン',type:'みつけた',sprite:`https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/${id}.png`,shiny:`https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/${id}.png`}));collection=normalise(collection);saveLocal();fillSuggestions();render()}catch(error){console.warn(error);fillSuggestions()}}
function visibleDex(){if(dexView==='caught')return collection;return[...dex.values()].map(p=>collection.find(c=>c.id===p.id)||{...p,photos:[],unknown:true})}
function render(){const list=$('#dexList');list.innerHTML='';visibleDex().sort((a,b)=>a.id-b.id).forEach(p=>{const caught=!p.unknown,n=$('#dexItemTemplate').content.cloneNode(true),card=n.querySelector('.dex-item'),photo=n.querySelector('.entry-photo'),normal=n.querySelector('.normal-sprite'),shiny=n.querySelector('.shiny-sprite');card.classList.toggle('unknown',!caught);photo.src=p.photos?.[0]||p.sprite;photo.alt=caught?p.name:'未登録のポケモン';normal.querySelector('img').src=p.sprite;shiny.querySelector('img').src=p.shiny;normal.hidden=!( !caught || (caught&&p.photos?.length));shiny.hidden=!caught;n.querySelector('.dex-no').textContent=`No.${pad(p.id)}`;n.querySelector('h3').textContent=caught?p.name:'？？？';n.querySelector('.type-pill').textContent=caught?p.type:'未登録';n.querySelector('.encounter').textContent=caught?(p.date||'まだ思い出はありません'):'見つけると登録できます';if(caught)card.onclick=()=>openEntry(p.id);list.append(n)});$('#seenCount').textContent=pad(collection.length);$('#photoCount').textContent=pad(collection.reduce((n,p)=>n+p.photos.length,0));$('#progressBar').style.width=`${Math.max(.1,collection.length/1025*100)}%`;$('#albumGrid').innerHTML=collection.flatMap(p=>p.photos.map(photo=>`<div class="album-card"><img src="${photo}" alt="${p.name}の写真"><span>No.${pad(p.id)} ${p.name}</span></div>`)).join('')||'<p>まだ写真がありません。</p>';renderMap()}
function renderMap(){const located=collection.filter(p=>Number.isFinite(p.lat)&&Number.isFinite(p.lng)),pins=$('#mapPins'),places=$('#placeList');pins.innerHTML='';if(!located.length){places.innerHTML='<div class="place-card"><span class="place-dot"></span><small>まだ位置情報がありません</small></div>';return}const minLat=Math.min(...located.map(p=>p.lat)),maxLat=Math.max(...located.map(p=>p.lat)),minLng=Math.min(...located.map(p=>p.lng)),maxLng=Math.max(...located.map(p=>p.lng));located.forEach((p,i)=>{const x=maxLng===minLng?50:10+80*(p.lng-minLng)/(maxLng-minLng),y=maxLat===minLat?50:85-70*(p.lat-minLat)/(maxLat-minLat);pins.insertAdjacentHTML('beforeend',`<button class="map-pin" style="left:calc(${x}% - 14px);top:calc(${y}% - 14px)" title="${p.name}・${p.place||'場所未入力'}"><b>${i+1}</b></button>`)});places.innerHTML=located.map(p=>`<div class="place-card"><span class="place-dot"></span><div><strong>${p.name} — ${p.place||'場所未入力'}</strong><small>${p.lat.toFixed(5)}, ${p.lng.toFixed(5)}</small></div><button class="edit-place" data-id="${p.id}">編集</button></div>`).join('');places.querySelectorAll('.edit-place').forEach(b=>b.onclick=()=>openEntry(Number(b.dataset.id)))}
function updateRegistration(){const raw=$('#nameInput').value.trim(),match=dex.get(toKatakana(raw)),status=$('#nameStatus');if(match){selected=match;$('#resultName').textContent=match.name;$('#resultMeta').textContent=`No.${pad(match.id)} ・ ${match.kind}`;$('#resultSprite').style.backgroundImage=`url(${match.sprite})`;$('#resultCard').hidden=false;status.classList.add('found');status.lastElementChild.textContent=`No.${pad(match.id)} に登録します`}else{selected=null;$('#resultCard').hidden=true;status.classList.remove('found');status.lastElementChild.textContent=raw?'名前を探しています。':'名前を入力すると図鑑へ振り分けます'}$('#saveBtn').disabled=!raw;$('#saveBtn').classList.toggle('ready',Boolean(raw))}
function compressPhoto(file){return new Promise((resolve,reject)=>{const url=URL.createObjectURL(file),image=new Image();image.onload=()=>{const scale=Math.min(1,960/Math.max(image.naturalWidth,image.naturalHeight)),canvas=document.createElement('canvas');canvas.width=Math.round(image.naturalWidth*scale);canvas.height=Math.round(image.naturalHeight*scale);canvas.getContext('2d').drawImage(image,0,0,canvas.width,canvas.height);URL.revokeObjectURL(url);resolve(canvas.toDataURL('image/jpeg',.68))};image.onerror=()=>reject(new Error('photo'));image.src=url})}
async function uploadPhotos(p){if(!canSync||!authToken)return;for(let i=0;i<p.photos.length;i++){if(!p.photos[i].startsWith('data:'))continue;const blob=await(await fetch(p.photos[i])).blob(),path=`${room}/${p.id}-${i}.jpg`,r=await fetch(`${config.supabaseUrl}/storage/v1/object/dex-photos/${path}`,{method:'POST',headers:{...headers(),'Content-Type':'image/jpeg','x-upsert':'true'},body:blob});if(!r.ok)throw new Error('写真アップロードに失敗しました');p.photos[i]=`${config.supabaseUrl}/storage/v1/object/public/dex-photos/${path}`}}
async function sync(){if(!canSync)throw new Error('config.js のSupabase設定がありません');if(!authToken)throw new Error('右上のMからログインしてください');const uploads=await Promise.allSettled(collection.map(uploadPhotos)),payload=collection.map(p=>({id:p.id,room,name:p.name,kind:p.kind,type:p.type,sprite:p.sprite,photo:JSON.stringify(p.photos),date:p.date||null,place:p.place||null,lat:p.lat??null,lng:p.lng??null})),r=await fetch(`${config.supabaseUrl}/rest/v1/entries?on_conflict=room,id`,{method:'POST',headers:{...headers(),'Content-Type':'application/json',Prefer:'resolution=merge-duplicates'},body:JSON.stringify(payload)});if(!r.ok){const problem=await r.json().catch(()=>({}));throw new Error(problem.message||`通信エラー ${r.status}`)}saveLocal();if(uploads.some(x=>x.status==='rejected'))showToast('図鑑は共有済み。写真は次回再同期します')}
async function loadShared(){if(!canSync||!authToken)return;try{const r=await fetch(`${config.supabaseUrl}/rest/v1/entries?room=eq.${encodeURIComponent(room)}&select=*`,{headers:headers()}),shared=await r.json();if(Array.isArray(shared)){const remote=normalise(shared),merged=new Map(remote.map(p=>[p.id,p]));collection.forEach(p=>{if(!merged.has(p.id))merged.set(p.id,p)});collection=[...merged.values()];saveLocal();render()}}catch(error){console.warn(error)}}
function resetForm(){$('#captureForm').reset();uploadedPhoto=selected=coordinates=null;$('#photoPreview').className='picker-inner';$('#photoPreview').style.backgroundImage='';$('#resultCard').hidden=true;updateRegistration();$('#locationState').textContent='場所はあとから編集できます'}
async function saveEntry(){const raw=$('#nameInput').value.trim(),p=selected;if(!raw){showToast('名前を入れてね');return}if(!p){showToast('候補からポケモンを選んでね');return}let entry=collection.find(item=>item.id===p.id);if(!entry){entry={...p,photos:[],date:'',place:'',lat:null,lng:null};collection.push(entry)}if(uploadedPhoto)entry.photos.push(uploadedPhoto);entry.photos=[...new Set(entry.photos)];entry.date=$('#noteInput').value.trim()||entry.date||'きょう ・ ふたりで発見';entry.place=$('#locationInput').value.trim()||entry.place;if(coordinates){entry.lat=coordinates.lat;entry.lng=coordinates.lng}saveLocal();render();$('#captureDialog').close();resetForm();showToast(`${p.name} を図鑑に登録したよ！`);try{await sync()}catch(error){showToast(`端末には保存済み：${error.message}`)}}
function openEntry(id){const p=collection.find(item=>item.id===id);if(!p)return;editId=id;editPhoto=null;$('#entryTitle').textContent=`${p.name} のきろく`;$('#entrySprite').src=p.sprite;$('#entryNo').textContent=`No.${pad(p.id)}`;$('#entryName').textContent=p.name;$('#entryKind').textContent=p.kind;$('#entryPhotos').innerHTML=p.photos.map(src=>`<img src="${src}" alt="${p.name}の写真">`).join('');$('#editNoteInput').value=p.date||'';$('#editPlaceInput').value=p.place||'';$('#editPhotoInput').value='';$('#entryDialog').showModal()}
function accountState(){const logged=Boolean(authToken);$('#accountHelp').textContent=logged?'この端末は図鑑アカウントにログイン中です。':'二人とも同じメールアドレスとパスワードでログインします。';$('#loginButton').hidden=logged;$('#signupButton').hidden=logged;$('#logoutButton').hidden=!logged;$('#accountButton').textContent=logged?'✓':'M'}
async function auth(mode){if(!canSync){$('#accountHelp').textContent='先に config.js を設定してください。';return}const email=$('#emailInput').value.trim(),password=$('#passwordInput').value;if(!email||password.length<6){$('#accountHelp').textContent='メールアドレスと6文字以上のパスワードを入力してください。';return}const r=await fetch(`${config.supabaseUrl}/auth/v1/${mode==='login'?'token?grant_type=password':'signup'}`,{method:'POST',headers:{apikey:config.supabaseAnonKey,'Content-Type':'application/json'},body:JSON.stringify({email,password})}),data=await r.json();if(!r.ok){$('#accountHelp').textContent=data.message||data.msg||'ログインできません。';return}if(!data.access_token){$('#accountHelp').textContent='メール確認後にログインしてください。';return}authToken=data.access_token;localStorage.setItem('futari-dex-token',authToken);accountState();await loadShared();$('#accountDialog').close()}
$('#openCapture').onclick=$('#captureCta').onclick=()=>$('#captureDialog').showModal();$('#nameInput').oninput=updateRegistration;$('#photoInput').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{uploadedPhoto=await compressPhoto(file);const preview=$('#photoPreview');preview.classList.add('preview');preview.style.backgroundImage=`url(${uploadedPhoto})`}catch{showToast('写真を読み込めませんでした')}};$('#locateBtn').onclick=()=>navigator.geolocation?.getCurrentPosition(p=>{coordinates={lat:p.coords.latitude,lng:p.coords.longitude};$('#locationState').textContent='位置情報を記録しました'},()=>$('#locationState').textContent='場所名だけでも登録できます');window.futariSaveEntry=saveEntry;$('#captureForm').onsubmit=e=>{e.preventDefault();saveEntry()};
$('#editPhotoInput').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{editPhoto=await compressPhoto(file);$('#entryPhotos').insertAdjacentHTML('beforeend',`<img src="${editPhoto}" alt="追加写真">`)}catch{showToast('写真を読み込めませんでした')}};$('#entryForm').onsubmit=async e=>{e.preventDefault();const p=collection.find(item=>item.id===editId);if(!p)return;p.date=$('#editNoteInput').value.trim()||p.date;p.place=$('#editPlaceInput').value.trim()||p.place;if(editPhoto)p.photos.push(editPhoto);p.photos=[...new Set(p.photos)];saveLocal();render();$('#entryDialog').close();try{await sync();showToast('変更を保存したよ！')}catch(error){showToast(`端末には保存済み：${error.message}`)}};
$('#deleteEntryButton').onclick=async()=>{const p=collection.find(item=>item.id===editId);if(!p||!confirm(`${p.name} を削除しますか？`))return;collection=collection.filter(item=>item.id!==p.id);saveLocal();render();$('#entryDialog').close();try{await fetch(`${config.supabaseUrl}/rest/v1/entries?room=eq.${encodeURIComponent(room)}&id=eq.${p.id}`,{method:'DELETE',headers:headers()});showToast('削除したよ')}catch{showToast('端末から削除したよ')}};
document.querySelectorAll('[data-dex-view]').forEach(button=>button.onclick=()=>{dexView=button.dataset.dexView;document.querySelectorAll('[data-dex-view]').forEach(b=>b.classList.toggle('active',b===button));render()});document.querySelectorAll('.tabs button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tabs button,.tab-panel').forEach(e=>e.classList.remove('active'));b.classList.add('active');$('#'+b.dataset.tab).classList.add('active')});const openTab=id=>{document.querySelector(`.tabs button[data-tab="${id}"]`).click();$('#menuDialog').close()};$('#menuButton').onclick=()=>$('#menuDialog').showModal();$('#menuDex').onclick=()=>openTab('dex');$('#menuMap').onclick=()=>openTab('map');$('#menuAlbum').onclick=()=>openTab('album');$('#accountButton').onclick=()=>$('#accountDialog').showModal();$('#loginButton').onclick=()=>auth('login');$('#signupButton').onclick=()=>auth('signup');$('#logoutButton').onclick=()=>{authToken='';localStorage.removeItem('futari-dex-token');accountState();$('#accountDialog').close()};
accountState();fillSuggestions();render();loadNationalDex();loadShared();
